name: easy_cook
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  provider: ^4.3.1
  flutter_svg: ^0.20.0-nullsafety.3
  dcdg: ^3.1.0
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  youtube_player_flutter: ^8.0.0
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+22
  simple_speed_dial: ^0.1.3
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/BeforeSignin/chef.png
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets\fonts\Pacifico\Pacifico-Regular.ttf

    - family: Caveat
      fonts:
        - asset: assets\fonts\Caveat\static\Caveat-Regular.ttf

    - family: Crimson
      fonts:
        - asset: assets\fonts\Crimson\CrimsonText-Bold.ttf
        - asset: assets\fonts\Crimson\CrimsonText-Regular.ttf
